# Generated by Django 2.0.7 on 2018-07-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0002_friendinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendinvitation',
            old_name='inviter_friend',
            new_name='invited_friend',
        ),
    ]
