# Generated by Django 2.0.7 on 2018-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0003_auto_20180717_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_customprofile_friends_+', to='custom_profile.CustomProfile'),
        ),
    ]
